### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by aaaz425** [project-Masil/masil-fe#1]
## 🎯 Feature

- 프로젝트 초기 세팅

## ✅ Tasks

- [x] 이슈, pr 템플릿 설정
- [x] cna를 통해 프로젝트 생성
- [x] 필요 패키지 설치
- [x] eslint, prettier 설정
- [x] 폴더 구조 작업
- [x] storybook 세팅
- [x] msw 세팅
- [x] 디자인 시스템 구축
- [x] jest, react-testling-library 세팅
- [x] vercel, github Actions 활용한 CI/CD 환경 구축
