### ISSUE TITLE
홈 화면 재작업

### ISSUE THREAD

**Issue by aaaz425** [project-Masil/masil-fe#24]
## 🎯 Feature

- 홈 화면 재작업

## ✅ Tasks

- [x] 헤더 재작업
- [x] 사이드 네비게이션 바 기능 구현
- [x] 홈 화면 재작업
- [x] 리뷰 리스트 필터 기능 추가
- [x] 추천 게시물 기능 추가
