### ISSUE TITLE
검색 엔진 최적화

### ISSUE THREAD

**Issue by aaaz425** [project-Masil/masil-fe#34]
## 🎯 Feature

- 검색 엔진 최적화 대비

## ✅ Tasks

- [ ] robot 파일 생성
- [ ] 메타태그 설정
- [ ] 검색 엔진에 웹사이트 등록
- [ ] SEO 점수 산정 및 보완
