### ISSUE TITLE
성능 최적화

### ISSUE THREAD

**Issue by aaaz425** [project-Masil/masil-fe#37]
## 🎯 Feature

- 성능 최적화하기

## ✅ Tasks

- [ ] 번들 크기 줄이기
- [ ] 이미지 최적화 (next Image)
- [ ] 캐싱 최대 활용
- [ ] 서버 컴포넌트 최대 활용
